---
sounds:  # a sounds key and it's path
    a:    sounds/dmk00_original/024-c0.wav
    b:    sounds/dmk00_original/025-c#0.wav
    c:    sounds/dmk00_original/026-d0.wav
    d:    sounds/dmk00_original/027-d#0.wav
    e:    sounds/dmk00_original/028-e0.wav
    f:    sounds/dmk00_original/029-f0.wav
    g:    sounds/dmk00_original/030-f#0.wav
    h:    sounds/dmk00_original/031-g0.wav
    i:    sounds/dmk00_original/032-g#0.wav
    j:    sounds/dmk00_original/033-a0.wav


keyboard:  # keys for different actions
    loop_begin: "["
    loop_end: "]"


grid:  # parameters related to the grid
    ticks: 4  #  tick-marking distance
    global_bpm: 120
    empty_space_chr: "."
    runner_chr: "|"
    loop_begin_chr: "["
    loop_end_chr: "]"
    bpm_on: "-"
    bpm_off: "~"


frame_rate: 12